# TODO:
# 1) Merge addr and reset into an inline table for registers. 
#    Helps keep the the corresponding addr and resets together
#    (e.g. CR1 = {addr = 0x0, reset = 0x0} )
# 2) Change 'addr' in 'flag' inline tables to 'PCaddr' so it's more descriptive
# 2) Find better way to ignore keys than '0xFFFF' when user doesn't want to use the key.
# 3) Add a way to change the flag count under 'flags' table. (e.g. Flag1 - Flagx)
# 4) Can make an inline table for memory map to add additional 'alias' option to memory regions.
# 5) Configuration registers could return to make certain flags configurable for interrupts.
# 6) Give option to provide an address for an IRQ rather than IRQn. Can compute irqn from address. 


[config]
[config.core]
cpu_model = "cortex-m4"
num_irq = 480
bitband = 1

[config.mem_map]
flash_base = 0x0
flash_size = 0x1f40000
sram_base = 0x1fff0000
sram_size = 0x3e800
sram_base2 = 0x0
sram_size2 = 0x0
sram_base3 = 0x0
sram_size3 = 0x0
    

    
[mmio]
[mmio.count]
uart_count = 1

    [mmio.uart]
    [mmio.uart.0]
    [mmio.uart.0.config]
    CR_count = 4
    SR_count = 4
    DR_count = 1
    flag_count = 0

    [mmio.uart.0.addr]
    base_addr = 0x4006A000
    CR1_addr = 0x4006a003   # Rx/Tx Interrupt Enable Bits
    CR2_addr = 0x4006a013   # TX Watermark  
    CR3_addr = 0x4006a015   # RX Watermark
    CR4_addr = 0x4006a020   # Interrupt Clear
    SR1_addr = 0x4006a004   # RX interrupt set bit is here
    SR2_addr = 0x4006A014   # Tx FIFO Count
    SR3_addr = 0x4006a021   # Tx FIFO Size
    SR4_addr = 0x4006a022   # Tx FIFO Full Flag
    DR1_addr = 0x4006a007   

    [mmio.uart.0.reset]
    CR1_reset = 0x0
    CR2_reset = 0x0
    CR3_reset = 0x1
    CR4_reset = 0
    SR1_reset = 0xC0
    SR2_reset = 0x0 
    SR3_reset = 0x0
    SR4_reset = 0x00        # This needs to be 0x80 when polarity=0   
    DR1_reset = 0x0
    
    [mmio.uart.0.hardware]
    RXFIFO_Size = 16
    TXFIFO_Size = 16
    
    [mmio.uart.0.interrupts]
    [mmio.uart.0.interrupts.RX]
    IRQn = "none"
    Emulation_Mode = "full"
    Intr_Enable = {CR = "none", bit = 0}
    Intr_Disable = {CR = "none", bit = 0}
    Intr_Status = {SR = "none", bit = 0}
    Intr_Clear = {CR = "none"}    
    Trigger = 0

    [mmio.uart.0.interrupts.TX]
    IRQn = "none"
    Emulation_Mode = "full"
    Intr_Enable = {CR = "none", bit = 0}
    Intr_Disable = {CR = "none", bit = 0}
    Intr_Status = {SR = "none", bit = 0} 
    Intr_Clear = {CR = "none"}    
    FIFO_Full = {SR = "none", bit = 0, polarity = 1}
    FIFO_Size = {SR = "none"} 
    FIFO_Count = {SR = "none"}        
    Trigger = 0
    
    [mmio.uart.0.interface]
    host = "stdio"
    guest = "serial"
        
    [mmio.uart.0.flags]
    

