# TODO
# 1) Find better way to ignore keys than '0xFFFF' when user doesn't want to use the key.
# 2) Add a way to change the flag count. e.g. Generic_Flag1 -> Generic_Flagx

[config]
[config.options]
core = 0
mem_map = 0

[mmio]
[mmio.count]
uart_count = 0
gpio_count = 0
generic_count = 1					

    [mmio.generic]
    [mmio.generic.0]
    [mmio.generic.0.config]
    SR_count = 1
    DR_count = 0

    [mmio.generic.0.addr]
    base_addr = 0x40064000
    SR1_addr = 0x40064006

    [mmio.generic.0.reset]
    SR1_reset = 0x0

    [mmio.generic.0.flags]
    Flag1 = {reg = "SR1", bit = 4, val = 1, addr = "optional"}
    Flag2 = {reg = "SR1", bit = 3, val = 1, addr = 0x19f2}
    Flag3 = {reg = "SR1", bit = 5, val = 0, addr = "optional"}
    Flag4 = {reg = "SR1", bit = 6, val = 1, addr = "optional"}
    Flag5 = {reg = "SR1", bit = 2, val = 1, addr = 0x1aec}
    Flag6 = {reg = "SR1", bit = 3, val = 1, addr = 0x1a86}
    Flag7 = {reg = "SR1", bit = 5, val = 1, addr = 0x1a9c}



