# Details code & data to be written to memory. Defines entry/exit points.
[firmware]
	[firmware.code]
	code_addr	= 0x00008018	# .text start
	code_size	= 0xFFFF	    # .text size determined by file size at the moment

	[firmware.data]
	data_addr	= 0x00018730	# .data start
	data_size	= 0xFFFF		# .data size determined by file size at the moment
	
	[firmware.execution]
	entry		= 0x0000824c	# start of main
	end  		= 0x00008278	# end of main

# Define memory map for your MCU
[mem_map]
# mem_map.flash
flash_addr 	= 0x00000000
flash_size 	= 0x00019000

# mem_map.sram
# SP, FP init to 
sram_addr 	= 0x02000000
sram_size 	= 0x00020000

# ARM mmio map 0x40000000 - 0x5fffffff
[mmio.count]
uart_count	= 2								
gpio_count 	= 3								
	
	[mmio.uart.0.config]
	SR_count = 2
	DR_count = 2
	
	[mmio.uart.0.addr]
	base_addr 	= 0x40013800	# Base address for uart0		
	SR1_addr	= 0x1c			# ISR
	SR2_addr	= 0xFFFF		# SKIP
	DR1_addr	= 0x24			# TDR
	DR2_addr	= 0x28			# RDR
		
	[mmio.uart.0.reset]
	SR1_reset	= 0x020000C0
	SR2_reset	= 0x00			# SKIP
	DR1_reset	= 0x00
	DR2_reset	= 0x00
	
	[mmio.uart.0.flags]
	TX_data_empty = {reg = "SR1", bit = 7}
	RX_data_full  = {reg = "SR1", bit = 5}
	TX_Complete   = {reg = "SR1", bit = 6}
	RX_enable_ack = {reg = "SR1", bit = 22}
	TX_enable_ack = {reg = "SR1", bit = 21}
	
    [mmio.uart.1]
    [mmio.uart.1.config]
    SR_count = 2
    DR_count = 2

    [mmio.uart.1.addr]
    base_addr = 0x40000000
    SR1_addr = 0x0
    SR2_addr = 0x0
    DR1_addr = 0x0
    DR2_addr = 0x0

    [mmio.uart.1.reset]
    SR1_reset = 0x0
    SR2_reset = 0x0
    DR1_reset = 0x0
    DR2_reset = 0x0

    [mmio.uart.1.flags]
    TX_data_empty = {reg = "reg", bit = 0}
    RX_data_full = {reg = "reg", bit = 0}
    TX_Complete = {reg = "reg", bit = 0}
    RX_enable_ack = {reg = "reg", bit = 0}
    TX_enable_ack = {reg = "reg", bit = 0}

    [mmio.gpio]
    [mmio.gpio.0]
    [mmio.gpio.0.config]
    SR_count = 2
    DR_count = 2

    [mmio.gpio.0.addr]
    base_addr = 0x40000000
    SR1_addr = 0x0
    SR2_addr = 0x0
    DR1_addr = 0x0
    DR2_addr = 0x0

    [mmio.gpio.0.reset]
    SR1_reset = 0x0
    SR2_reset = 0x0
    DR1_reset = 0x0
    DR2_reset = 0x0

    [mmio.gpio.0.flags]
    Generic_Flag1 = {reg = "reg", bit = 0}
    Generic_Flag2 = {reg = "reg", bit = 0}
    Generic_Flag3 = {reg = "reg", bit = 0}

    [mmio.gpio.1]
    [mmio.gpio.1.config]
    SR_count = 2
    DR_count = 2

    [mmio.gpio.1.addr]
    base_addr = 0x40000000
    SR1_addr = 0x0
    SR2_addr = 0x0
    DR1_addr = 0x0
    DR2_addr = 0x0

    [mmio.gpio.1.reset]
    SR1_reset = 0x0
    SR2_reset = 0x0
    DR1_reset = 0x0
    DR2_reset = 0x0

    [mmio.gpio.1.flags]
    Generic_Flag1 = {reg = "reg", bit = 0}
    Generic_Flag2 = {reg = "reg", bit = 0}
    Generic_Flag3 = {reg = "reg", bit = 0}

    [mmio.gpio.2]
    [mmio.gpio.2.config]
    SR_count = 2
    DR_count = 2

    [mmio.gpio.2.addr]
    base_addr = 0x40000000
    SR1_addr = 0x0
    SR2_addr = 0x0
    DR1_addr = 0x0
    DR2_addr = 0x0

    [mmio.gpio.2.reset]
    SR1_reset = 0x0
    SR2_reset = 0x0
    DR1_reset = 0x0
    DR2_reset = 0x0

    [mmio.gpio.2.flags]
    Generic_Flag1 = {reg = "reg", bit = 0}
    Generic_Flag2 = {reg = "reg", bit = 0}
    Generic_Flag3 = {reg = "reg", bit = 0}
