[config]
[config.core]
cpu_model = "cortex-m4"
num_irq = 480
bitband = 1

[config.mem_map]
flash_base = 0x0
flash_size = 0x1f40000
sram_base = 0x1fff0000
sram_size = 0x3e800
sram_base2 = 0x0
sram_size2 = 0x0
sram_base3 = 0x0
sram_size3 = 0x0
   
    
[mmio]
[mmio.count]
uart_count = 1		

    [mmio.uart]
    [mmio.uart.0]
    [mmio.uart.0.config]
    peripheral_type = "default"
    CR_count = 1
    SR_count = 1
    DR_count = 1
    flag_count = 2

    [mmio.uart.0.addr]
    base_addr = 0x0
    CR1_addr = 0x0
    SR1_addr = 0x0
    DR1_addr = 0x0

    [mmio.uart.0.reset]
    CR1_reset = 0x0
    SR1_reset = 0x0
    DR1_reset = 0x0

    [mmio.uart.0.interrupts]

    [mmio.uart.0.flags]
    Flag1 = {reg = "reg", bit = 0, val = 1, addr = "optional"}
    Flag2 = {reg = "reg", bit = 0, val = 1, addr = "optional"}
