# Details code & data to be written to memory. Defines entry/exit points.
[firmware]
	[firmware.code]
	code_addr	= 0x00008018	# .text start
	code_size	= 0xFFFF	    # .text size determined by file size at the moment

	[firmware.data]
	data_addr	= 0x00018730	# .data start
	data_size	= 0xFFFF		# .data size determined by file size at the moment
	
	# Where firmware will begin and end execution
	[firmware.execution]
	entry		= 0x0000824c	# start of main
	end  		= 0x00008278	# end of main

# Define memory map for your MCU
[mem_map]
# mem_map.flash
flash_addr 	= 0x00000000
flash_size 	= 0x00019000

# mem_map.sram
# SP, FP init to 
sram_addr 	= 0x02000000
sram_size 	= 0x00020000

[mmio]
[mmio.count]
uart_count = 0
gpio_count = 0


