# TODO:
# 1) Merge addr and reset into an inline table for registers. 
#    Helps keep the the corresponding addr and resets together
#    (e.g. CR1 = {addr = 0x0, reset = 0x0} )
# 2) Change 'addr' in 'flag' inline tables to 'PCaddr' so it's more descriptive
# 2) Find better way to ignore keys than '0xFFFF' when user doesn't want to use the key.
# 3) Add a way to change the flag count under 'flags' table. (e.g. Flag1 - Flagx)
# 4) Can make an inline table for memory map to add additional 'alias' option to memory regions.
# 5) Configuration registers could return to make certain flags configurable for interrupts.
# 6) Give option to provide an address for an IRQ rather than IRQn. Can compute irqn from address. 


[config]
[config.options]
core = 1
mem_map = 1

    [config.mem_map]
    flash_base = 0x0
    flash_size = 0x1f40000
    sram_base = 0x1fff0000
    sram_size = 0x3e800
    sram_base2 = 0x0
    sram_size2 = 0x0
    sram_base3 = 0x0
    sram_size3 = 0x0
    
    [config.core]
    cpu_model = "cortex-m4"
    num_irq = 480
    bitband = 1
    
[mmio]
[mmio.count]
mcg_count = 1       # Multi-purpose clock generator	
uart_count = 1
test_count = 1
				
    [mmio.mcg]
    [mmio.mcg.0]
    [mmio.mcg.0.config]
    CR_count = 0
    SR_count = 1
    DR_count = 0
    flag_count = 14

    [mmio.mcg.0.addr]
    base_addr = 0x40064000
    SR1_addr = 0x40064006

    [mmio.mcg.0.reset]
    SR1_reset = 0x0
    
    [mmio.mcg.0.interrupts]
    
    
    [mmio.mcg.0.flags]
    Flag1 = {reg = "SR1", bit = 4, val = 1, addr = "optional"}
    Flag2 = {reg = "SR1", bit = 3, val = 1, addr = 0x19f2}
    Flag3 = {reg = "SR1", bit = 5, val = 0, addr = "optional"}
    Flag4 = {reg = "SR1", bit = 6, val = 1, addr = "optional"}
    Flag5 = {reg = "SR1", bit = 2, val = 1, addr = 0x1aec}
    Flag6 = {reg = "SR1", bit = 3, val = 1, addr = 0x1a86}
    Flag7 = {reg = "SR1", bit = 5, val = 1, addr = 0x1a9c}
    Flag8 = {reg = "SR1", bit = 3, val = 1, addr = 0xf34}      
    Flag9 = {reg = "SR1", bit = 5, val = 1, addr = 0xfb4}
    Flag10 = {reg = "SR1", bit = 3, val = 1, addr = 0xf7c}
    Flag11 = {reg = "SR1", bit = 2, val = 1, addr = 0xf7c}
    Flag12 = {reg = "SR1", bit = 3, val = 0, addr = 0x104c} # Was 0x104c
    Flag13 = {reg = "SR1", bit = 2, val = 0, addr = 0x104c} # Was 0x104c
    Flag14 = {reg = "SR1", bit = 5, val = 0, addr = 0x102c}
    Flag15 = {reg = "SR1", bit = 5, val = 0, addr = 0x102c}

    [mmio.uart]
    [mmio.uart.0]
    [mmio.uart.0.config]
    CR_count = 7
    SR_count = 1
    DR_count = 1
    flag_count = 1

    [mmio.uart.0.addr]
    base_addr = 0x4006A000
    CR1_addr = 0x4006a000
    CR2_addr = 0x4006a001   
    CR3_addr = 0x4006a002   
    CR4_addr = 0x4006a003   # RXFIFO interrupt enable bit is here
    CR5_addr = 0x4006a008
    CR6_addr = 0x4006a00c   
    CR7_addr = 0x4006a015   # FIFO RX Watermark (RXWATER)
    SR1_addr = 0x4006a004   # RXFIFO interrupt set bit is here
    DR1_addr = 0x4006a007   # DR

    [mmio.uart.0.reset]
    CR1_reset = 0x0
    CR2_reset = 0x0
    CR3_reset = 0x0
    CR4_reset = 0x0
    CR5_reset = 0x0
    CR6_reset = 0x0
    CR7_reset = 0x1     # FIFO RX Watermark (RXWATER) 
    SR1_reset = 0xC0    
    DR1_reset = 0x0
    
    [mmio.uart.0.hardware]
    RXFIFO_Size = 16
    TXFIFO_Size = 16
    
    [mmio.uart.0.interrupts]
    [mmio.uart.0.interrupts.RX]
    IRQn = 31
    Emulation_Mode = "full"
    Intr_Enable = {CR = "CR4", bit = 5}
    Intr_Disable = {CR = "none", bit = 0}
    Intr_Status = {SR = "SR1", bit = 5}
    Intr_Clear = {CR = "none"}    
    Trigger = 1                         # 1 should be the default here

    [mmio.uart.0.interrupts.TX]
    IRQn = 32
    Emulation_Mode = "full"
    Intr_Enable = {CR = "CR4", bit = 5}
    Intr_Disable = {CR = "none", bit = 0}
    Intr_Status = {SR = "SR1", bit = 5} 
    Intr_Clear = {CR = "none"}    
    Tx_Enable = {CR = "none", bit = 0}
    Tx_Disable = {CR = "none", bit = 0}  
    Trigger = "none"                    # "none" should be the default here
    
    [mmio.uart.0.interface]
    host = "stdio"
    guest = "serial"    
        
    [mmio.uart.0.flags]
    Flag1 = {reg = "SR1", bit = 7, val = 1, addr = 0xdca}       

    [mmio.test]
    [mmio.test.0]
    [mmio.test.0.config]
    CR_count = 2
    SR_count = 2
    DR_count = 2
    flag_count = 2

    [mmio.test.0.addr]
    base_addr = 0x0
    CR1_addr = 0x0
    CR2_addr = 0x0
    SR1_addr = 0x0
    SR2_addr = 0x0
    DR1_addr = 0x0
    DR2_addr = 0x0

    [mmio.test.0.reset]
    CR1_reset = 0x0
    CR2_reset = 0x0
    SR1_reset = 0x0
    SR2_reset = 0x0
    DR1_reset = 0x0
    DR2_reset = 0x0

    [mmio.test.0.interrupts]
    
    [mmio.test.0.flags]
    Flag1 = {reg = "reg", bit = 0, val = 1, addr = "optional"}
    Flag2 = {reg = "reg", bit = 0, val = 1, addr = "optional"}
