[config]
[config.options]
core = 1
mem_map = 1

    # TODO: Memory size could be off
    [config.mem_map]
    flash_base = 0x0
    flash_size = 256000
    sram_base = 0x20000000
    sram_size = 32000
    sram_base2 = 0x0
    sram_size2 = 0x0
    sram_base3 = 0x0
    sram_size3 = 0x0
    
    [config.core]
    cpu_model = "cortex-m4"
    num_irq = 480
    bitband = 1
    
[mmio]
[mmio.count]
uart_count = 1

    # TODO: Configure only registers which are used
    [mmio.uart]
    [mmio.uart.0]
    [mmio.uart.0.config]
    CR_count = 2
    SR_count = 1
    DR_count = 1
    flag_count = 1

    [mmio.uart.0.addr]
    base_addr = 0x4006A000 
    CR1_addr = 0x4006a003   # RXFIFO interrupt enable bit is here  
    CR2_addr = 0x4006a015   # FIFO RX Watermark (RXWATER)
    SR1_addr = 0x4006a004   # RXFIFO interrupt set bit is here
    DR1_addr = 0x4006a007   # DR

    [mmio.uart.0.reset]
    CR1_reset = 0x0
    CR2_reset = 0x1         # FIFO RX Watermark (RXWATER) 
    SR1_reset = 0xC0    
    DR1_reset = 0x0
    
    [mmio.uart.0.hardware]
    RXFIFO_Size = 16
    TXFIFO_Size = 16
    
    [mmio.uart.0.interrupts]
    [mmio.uart.0.interrupts.RX]
    IRQn = 31
    Emulation_Mode = "full"
    Intr_Enable = {CR = "CR4", bit = 5}
    Intr_Disable = {CR = "none", bit = 0}
    Intr_Status = {SR = "SR1", bit = 5}
    Intr_Clear = {CR = "none"}    
    Trigger = 1                         # 1 should be the default here

    [mmio.uart.0.interrupts.TX]
    IRQn = 32
    Emulation_Mode = "full"
    Intr_Enable = {CR = "CR4", bit = 5}
    Intr_Disable = {CR = "none", bit = 0}
    Intr_Status = {SR = "SR1", bit = 5} 
    Intr_Clear = {CR = "none"}    
    Tx_Enable = {CR = "none", bit = 0}
    Tx_Disable = {CR = "none", bit = 0}  
    Trigger = "none"                    # "none" should be the default here
    
    [mmio.uart.0.interface]
    host = "stdio"
    guest = "serial"    
        
    [mmio.uart.0.flags]
    Flag1 = {reg = "SR1", bit = 7, val = 1, addr = 0xdca}       

