#
# pkey = ["<peripheral_type>", 
#         Implemented?, 
#         ID, 
#         "<path>"]
#
# Implemented: Referring to 
# 1) TOML [hardware] and [interrupts] tables defined
# 2) Peripheral's parsing functions and data structure(s) in place to accept TOML parameters
# 3) Peripheral emulated in mmio callbacks via CR/SR/DR rw functions
#
# <path> refers to the peripheral's path to a TOML file that 
#        defines its [hardware] and [interrupts] tables completely.
#        You can use "peripherals/uart.toml" as an example.

periph0 = ["default", false, 0, "peripherals/<peripheral>.toml"]
periph1 = ["uart", true, 1, "peripherals/uart.toml"]
periph2 = ["default", false, 2, "peripherals/<peripheral>.toml"]
periph3 = ["default", false, 3, "peripherals/<peripheral>.toml"]
periph4 = ["default", false, 4, "peripherals/<peripheral>.toml"]
periph5 = ["default", false, 5, "peripherals/<peripheral>.toml"]
periph6 = ["default", false, 6, "peripherals/<peripheral>.toml"]
periph7 = ["default", false, 7, "peripherals/<peripheral>.toml"]
periph8 = ["default", false, 8, "peripherals/<peripheral>.toml"]
periph9 = ["default", false, 9, "peripherals/<peripheral>.toml"]
periph10 = ["default", false, 10, "peripherals/<peripheral>.toml"]
periph11 = ["default", false, 11, "peripherals/<peripheral>.toml"]
periph12 = ["default", false, 12, "peripherals/<peripheral>.toml"]
periph13 = ["default", false, 13, "peripherals/<peripheral>.toml"]
periph14 = ["default", false, 14, "peripherals/<peripheral>.toml"]
periph15 = ["default", false, 15, "peripherals/<peripheral>.toml"]
periph16 = ["default", false, 16, "peripherals/<peripheral>.toml"]
periph17 = ["default", false, 17, "peripherals/<peripheral>.toml"]
periph18 = ["default", false, 18, "peripherals/<peripheral>.toml"]
periph19 = ["default", false, 19, "peripherals/<peripheral>.toml"]
periph20 = ["default", false, 20, "peripherals/<peripheral>.toml"]
periph21 = ["default", false, 21, "peripherals/<peripheral>.toml"]
periph22 = ["default", false, 22, "peripherals/<peripheral>.toml"]
periph23 = ["default", false, 23, "peripherals/<peripheral>.toml"]
periph24 = ["default", false, 24, "peripherals/<peripheral>.toml"]
periph25 = ["default", false, 25, "peripherals/<peripheral>.toml"]
periph26 = ["default", false, 26, "peripherals/<peripheral>.toml"]
periph27 = ["default", false, 27, "peripherals/<peripheral>.toml"]
periph28 = ["default", false, 28, "peripherals/<peripheral>.toml"]
periph29 = ["default", false, 29, "peripherals/<peripheral>.toml"]
periph30 = ["default", false, 30, "peripherals/<peripheral>.toml"]
periph31 = ["default", false, 31, "peripherals/<peripheral>.toml"]
periph32 = ["default", false, 32, "peripherals/<peripheral>.toml"]
periph33 = ["default", false, 33, "peripherals/<peripheral>.toml"]
periph34 = ["default", false, 34, "peripherals/<peripheral>.toml"]
periph35 = ["default", false, 35, "peripherals/<peripheral>.toml"]
periph36 = ["default", false, 36, "peripherals/<peripheral>.toml"]
periph37 = ["default", false, 37, "peripherals/<peripheral>.toml"]
periph38 = ["default", false, 38, "peripherals/<peripheral>.toml"]
periph39 = ["default", false, 39, "peripherals/<peripheral>.toml"]
periph40 = ["default", false, 40, "peripherals/<peripheral>.toml"]
periph41 = ["default", false, 41, "peripherals/<peripheral>.toml"]
periph42 = ["default", false, 42, "peripherals/<peripheral>.toml"]
periph43 = ["default", false, 43, "peripherals/<peripheral>.toml"]
periph44 = ["default", false, 44, "peripherals/<peripheral>.toml"]
periph45 = ["default", false, 45, "peripherals/<peripheral>.toml"]
periph46 = ["default", false, 46, "peripherals/<peripheral>.toml"]
periph47 = ["default", false, 47, "peripherals/<peripheral>.toml"]
periph48 = ["default", false, 48, "peripherals/<peripheral>.toml"]
periph49 = ["default", false, 49, "peripherals/<peripheral>.toml"]
periph50 = ["default", false, 50, "peripherals/<peripheral>.toml"]
periph51 = ["default", false, 51, "peripherals/<peripheral>.toml"]
periph52 = ["default", false, 52, "peripherals/<peripheral>.toml"]
periph53 = ["default", false, 53, "peripherals/<peripheral>.toml"]
periph54 = ["default", false, 54, "peripherals/<peripheral>.toml"]
periph55 = ["default", false, 55, "peripherals/<peripheral>.toml"]
periph56 = ["default", false, 56, "peripherals/<peripheral>.toml"]
periph57 = ["default", false, 57, "peripherals/<peripheral>.toml"]
periph58 = ["default", false, 58, "peripherals/<peripheral>.toml"]
periph59 = ["default", false, 59, "peripherals/<peripheral>.toml"]
periph60 = ["default", false, 60, "peripherals/<peripheral>.toml"]
periph61 = ["default", false, 61, "peripherals/<peripheral>.toml"]
periph62 = ["default", false, 62, "peripherals/<peripheral>.toml"]
periph63 = ["default", false, 63, "peripherals/<peripheral>.toml"]
periph64 = ["default", false, 64, "peripherals/<peripheral>.toml"]
periph65 = ["default", false, 65, "peripherals/<peripheral>.toml"]
periph66 = ["default", false, 66, "peripherals/<peripheral>.toml"]
periph67 = ["default", false, 67, "peripherals/<peripheral>.toml"]
periph68 = ["default", false, 68, "peripherals/<peripheral>.toml"]
periph69 = ["default", false, 69, "peripherals/<peripheral>.toml"]
periph70 = ["default", false, 70, "peripherals/<peripheral>.toml"]
periph71 = ["default", false, 71, "peripherals/<peripheral>.toml"]
periph72 = ["default", false, 72, "peripherals/<peripheral>.toml"]
periph73 = ["default", false, 73, "peripherals/<peripheral>.toml"]
periph74 = ["default", false, 74, "peripherals/<peripheral>.toml"]
periph75 = ["default", false, 75, "peripherals/<peripheral>.toml"]
periph76 = ["default", false, 76, "peripherals/<peripheral>.toml"]
periph77 = ["default", false, 77, "peripherals/<peripheral>.toml"]
periph78 = ["default", false, 78, "peripherals/<peripheral>.toml"]
periph79 = ["default", false, 79, "peripherals/<peripheral>.toml"]
periph80 = ["default", false, 80, "peripherals/<peripheral>.toml"]
periph81 = ["default", false, 81, "peripherals/<peripheral>.toml"]
periph82 = ["default", false, 82, "peripherals/<peripheral>.toml"]
periph83 = ["default", false, 83, "peripherals/<peripheral>.toml"]
periph84 = ["default", false, 84, "peripherals/<peripheral>.toml"]
periph85 = ["default", false, 85, "peripherals/<peripheral>.toml"]
periph86 = ["default", false, 86, "peripherals/<peripheral>.toml"]
periph87 = ["default", false, 87, "peripherals/<peripheral>.toml"]
periph88 = ["default", false, 88, "peripherals/<peripheral>.toml"]
periph89 = ["default", false, 89, "peripherals/<peripheral>.toml"]
periph90 = ["default", false, 90, "peripherals/<peripheral>.toml"]
periph91 = ["default", false, 91, "peripherals/<peripheral>.toml"]
periph92 = ["default", false, 92, "peripherals/<peripheral>.toml"]
periph93 = ["default", false, 93, "peripherals/<peripheral>.toml"]
periph94 = ["default", false, 94, "peripherals/<peripheral>.toml"]
periph95 = ["default", false, 95, "peripherals/<peripheral>.toml"]
periph96 = ["default", false, 96, "peripherals/<peripheral>.toml"]
periph97 = ["default", false, 97, "peripherals/<peripheral>.toml"]
periph98 = ["default", false, 98, "peripherals/<peripheral>.toml"]
periph99 = ["default", false, 99, "peripherals/<peripheral>.toml"]
periph100 = ["default", false, 100, "peripherals/<peripheral>.toml"]
periph101 = ["default", false, 101, "peripherals/<peripheral>.toml"]
periph102 = ["default", false, 102, "peripherals/<peripheral>.toml"]
periph103 = ["default", false, 103, "peripherals/<peripheral>.toml"]
periph104 = ["default", false, 104, "peripherals/<peripheral>.toml"]
periph105 = ["default", false, 105, "peripherals/<peripheral>.toml"]
periph106 = ["default", false, 106, "peripherals/<peripheral>.toml"]
periph107 = ["default", false, 107, "peripherals/<peripheral>.toml"]
periph108 = ["default", false, 108, "peripherals/<peripheral>.toml"]
periph109 = ["default", false, 109, "peripherals/<peripheral>.toml"]
periph110 = ["default", false, 110, "peripherals/<peripheral>.toml"]
periph111 = ["default", false, 111, "peripherals/<peripheral>.toml"]
periph112 = ["default", false, 112, "peripherals/<peripheral>.toml"]
periph113 = ["default", false, 113, "peripherals/<peripheral>.toml"]
periph114 = ["default", false, 114, "peripherals/<peripheral>.toml"]
periph115 = ["default", false, 115, "peripherals/<peripheral>.toml"]
periph116 = ["default", false, 116, "peripherals/<peripheral>.toml"]
periph117 = ["default", false, 117, "peripherals/<peripheral>.toml"]
periph118 = ["default", false, 118, "peripherals/<peripheral>.toml"]
periph119 = ["default", false, 119, "peripherals/<peripheral>.toml"]
periph120 = ["default", false, 120, "peripherals/<peripheral>.toml"]
periph121 = ["default", false, 121, "peripherals/<peripheral>.toml"]
periph122 = ["default", false, 122, "peripherals/<peripheral>.toml"]
periph123 = ["default", false, 123, "peripherals/<peripheral>.toml"]
periph124 = ["default", false, 124, "peripherals/<peripheral>.toml"]
periph125 = ["default", false, 125, "peripherals/<peripheral>.toml"]
periph126 = ["default", false, 126, "peripherals/<peripheral>.toml"]
periph127 = ["default", false, 127, "peripherals/<peripheral>.toml"]
periph128 = ["default", false, 128, "peripherals/<peripheral>.toml"]
periph129 = ["default", false, 129, "peripherals/<peripheral>.toml"]
periph130 = ["default", false, 130, "peripherals/<peripheral>.toml"]
periph131 = ["default", false, 131, "peripherals/<peripheral>.toml"]
periph132 = ["default", false, 132, "peripherals/<peripheral>.toml"]
periph133 = ["default", false, 133, "peripherals/<peripheral>.toml"]
periph134 = ["default", false, 134, "peripherals/<peripheral>.toml"]
periph135 = ["default", false, 135, "peripherals/<peripheral>.toml"]
periph136 = ["default", false, 136, "peripherals/<peripheral>.toml"]
periph137 = ["default", false, 137, "peripherals/<peripheral>.toml"]
periph138 = ["default", false, 138, "peripherals/<peripheral>.toml"]
periph139 = ["default", false, 139, "peripherals/<peripheral>.toml"]
periph140 = ["default", false, 140, "peripherals/<peripheral>.toml"]
periph141 = ["default", false, 141, "peripherals/<peripheral>.toml"]
periph142 = ["default", false, 142, "peripherals/<peripheral>.toml"]
periph143 = ["default", false, 143, "peripherals/<peripheral>.toml"]
periph144 = ["default", false, 144, "peripherals/<peripheral>.toml"]
periph145 = ["default", false, 145, "peripherals/<peripheral>.toml"]
periph146 = ["default", false, 146, "peripherals/<peripheral>.toml"]
periph147 = ["default", false, 147, "peripherals/<peripheral>.toml"]
periph148 = ["default", false, 148, "peripherals/<peripheral>.toml"]
periph149 = ["default", false, 149, "peripherals/<peripheral>.toml"]
periph150 = ["default", false, 150, "peripherals/<peripheral>.toml"]
periph151 = ["default", false, 151, "peripherals/<peripheral>.toml"]
periph152 = ["default", false, 152, "peripherals/<peripheral>.toml"]
periph153 = ["default", false, 153, "peripherals/<peripheral>.toml"]
periph154 = ["default", false, 154, "peripherals/<peripheral>.toml"]
periph155 = ["default", false, 155, "peripherals/<peripheral>.toml"]
periph156 = ["default", false, 156, "peripherals/<peripheral>.toml"]
periph157 = ["default", false, 157, "peripherals/<peripheral>.toml"]
periph158 = ["default", false, 158, "peripherals/<peripheral>.toml"]
periph159 = ["default", false, 159, "peripherals/<peripheral>.toml"]
periph160 = ["default", false, 160, "peripherals/<peripheral>.toml"]
periph161 = ["default", false, 161, "peripherals/<peripheral>.toml"]
periph162 = ["default", false, 162, "peripherals/<peripheral>.toml"]
periph163 = ["default", false, 163, "peripherals/<peripheral>.toml"]
periph164 = ["default", false, 164, "peripherals/<peripheral>.toml"]
periph165 = ["default", false, 165, "peripherals/<peripheral>.toml"]
periph166 = ["default", false, 166, "peripherals/<peripheral>.toml"]
periph167 = ["default", false, 167, "peripherals/<peripheral>.toml"]
periph168 = ["default", false, 168, "peripherals/<peripheral>.toml"]
periph169 = ["default", false, 169, "peripherals/<peripheral>.toml"]
periph170 = ["default", false, 170, "peripherals/<peripheral>.toml"]
periph171 = ["default", false, 171, "peripherals/<peripheral>.toml"]
periph172 = ["default", false, 172, "peripherals/<peripheral>.toml"]
periph173 = ["default", false, 173, "peripherals/<peripheral>.toml"]
periph174 = ["default", false, 174, "peripherals/<peripheral>.toml"]
periph175 = ["default", false, 175, "peripherals/<peripheral>.toml"]
periph176 = ["default", false, 176, "peripherals/<peripheral>.toml"]
periph177 = ["default", false, 177, "peripherals/<peripheral>.toml"]
periph178 = ["default", false, 178, "peripherals/<peripheral>.toml"]
periph179 = ["default", false, 179, "peripherals/<peripheral>.toml"]
periph180 = ["default", false, 180, "peripherals/<peripheral>.toml"]
periph181 = ["default", false, 181, "peripherals/<peripheral>.toml"]
periph182 = ["default", false, 182, "peripherals/<peripheral>.toml"]
periph183 = ["default", false, 183, "peripherals/<peripheral>.toml"]
periph184 = ["default", false, 184, "peripherals/<peripheral>.toml"]
periph185 = ["default", false, 185, "peripherals/<peripheral>.toml"]
periph186 = ["default", false, 186, "peripherals/<peripheral>.toml"]
periph187 = ["default", false, 187, "peripherals/<peripheral>.toml"]
periph188 = ["default", false, 188, "peripherals/<peripheral>.toml"]
periph189 = ["default", false, 189, "peripherals/<peripheral>.toml"]
periph190 = ["default", false, 190, "peripherals/<peripheral>.toml"]
periph191 = ["default", false, 191, "peripherals/<peripheral>.toml"]
periph192 = ["default", false, 192, "peripherals/<peripheral>.toml"]
periph193 = ["default", false, 193, "peripherals/<peripheral>.toml"]
periph194 = ["default", false, 194, "peripherals/<peripheral>.toml"]
periph195 = ["default", false, 195, "peripherals/<peripheral>.toml"]
periph196 = ["default", false, 196, "peripherals/<peripheral>.toml"]
periph197 = ["default", false, 197, "peripherals/<peripheral>.toml"]
periph198 = ["default", false, 198, "peripherals/<peripheral>.toml"]
periph199 = ["default", false, 199, "peripherals/<peripheral>.toml"]
periph200 = ["default", false, 200, "peripherals/<peripheral>.toml"]
periph201 = ["default", false, 201, "peripherals/<peripheral>.toml"]
periph202 = ["default", false, 202, "peripherals/<peripheral>.toml"]
periph203 = ["default", false, 203, "peripherals/<peripheral>.toml"]
periph204 = ["default", false, 204, "peripherals/<peripheral>.toml"]
periph205 = ["default", false, 205, "peripherals/<peripheral>.toml"]
periph206 = ["default", false, 206, "peripherals/<peripheral>.toml"]
periph207 = ["default", false, 207, "peripherals/<peripheral>.toml"]
periph208 = ["default", false, 208, "peripherals/<peripheral>.toml"]
periph209 = ["default", false, 209, "peripherals/<peripheral>.toml"]
periph210 = ["default", false, 210, "peripherals/<peripheral>.toml"]
periph211 = ["default", false, 211, "peripherals/<peripheral>.toml"]
periph212 = ["default", false, 212, "peripherals/<peripheral>.toml"]
periph213 = ["default", false, 213, "peripherals/<peripheral>.toml"]
periph214 = ["default", false, 214, "peripherals/<peripheral>.toml"]
periph215 = ["default", false, 215, "peripherals/<peripheral>.toml"]
periph216 = ["default", false, 216, "peripherals/<peripheral>.toml"]
periph217 = ["default", false, 217, "peripherals/<peripheral>.toml"]
periph218 = ["default", false, 218, "peripherals/<peripheral>.toml"]
periph219 = ["default", false, 219, "peripherals/<peripheral>.toml"]
periph220 = ["default", false, 220, "peripherals/<peripheral>.toml"]
periph221 = ["default", false, 221, "peripherals/<peripheral>.toml"]
periph222 = ["default", false, 222, "peripherals/<peripheral>.toml"]
periph223 = ["default", false, 223, "peripherals/<peripheral>.toml"]
periph224 = ["default", false, 224, "peripherals/<peripheral>.toml"]
periph225 = ["default", false, 225, "peripherals/<peripheral>.toml"]
periph226 = ["default", false, 226, "peripherals/<peripheral>.toml"]
periph227 = ["default", false, 227, "peripherals/<peripheral>.toml"]
periph228 = ["default", false, 228, "peripherals/<peripheral>.toml"]
periph229 = ["default", false, 229, "peripherals/<peripheral>.toml"]
periph230 = ["default", false, 230, "peripherals/<peripheral>.toml"]
periph231 = ["default", false, 231, "peripherals/<peripheral>.toml"]
periph232 = ["default", false, 232, "peripherals/<peripheral>.toml"]
periph233 = ["default", false, 233, "peripherals/<peripheral>.toml"]
periph234 = ["default", false, 234, "peripherals/<peripheral>.toml"]
periph235 = ["default", false, 235, "peripherals/<peripheral>.toml"]
periph236 = ["default", false, 236, "peripherals/<peripheral>.toml"]
periph237 = ["default", false, 237, "peripherals/<peripheral>.toml"]
periph238 = ["default", false, 238, "peripherals/<peripheral>.toml"]
periph239 = ["default", false, 239, "peripherals/<peripheral>.toml"]
periph240 = ["default", false, 240, "peripherals/<peripheral>.toml"]
periph241 = ["default", false, 241, "peripherals/<peripheral>.toml"]
periph242 = ["default", false, 242, "peripherals/<peripheral>.toml"]
periph243 = ["default", false, 243, "peripherals/<peripheral>.toml"]
periph244 = ["default", false, 244, "peripherals/<peripheral>.toml"]
periph245 = ["default", false, 245, "peripherals/<peripheral>.toml"]
periph246 = ["default", false, 246, "peripherals/<peripheral>.toml"]
periph247 = ["default", false, 247, "peripherals/<peripheral>.toml"]
periph248 = ["default", false, 248, "peripherals/<peripheral>.toml"]
periph249 = ["default", false, 249, "peripherals/<peripheral>.toml"]
periph250 = ["default", false, 250, "peripherals/<peripheral>.toml"]
periph251 = ["default", false, 251, "peripherals/<peripheral>.toml"]
periph252 = ["default", false, 252, "peripherals/<peripheral>.toml"]
periph253 = ["default", false, 253, "peripherals/<peripheral>.toml"]
periph254 = ["default", false, 254, "peripherals/<peripheral>.toml"]
periph255 = ["default", false, 255, "peripherals/<peripheral>.toml"]
