#
# peripheral_type template entries
#
# pkey = ["<peripheral_type>", 
#         Implemented?, 
#         ID, 
#         "<path>"]
# 
# @ <peripheral_type>: Unique string ID for peripheral.
#                      Synonymous with <peripheral> 
#
# @ Implemented: Referring to 
#   1) TOML [hardware] and [interrupts] table templates defined
#   2) Peripheral's parsing functions and data structure(s) in place to accept TOML parameters
#   3) Peripheral emulated in mmio callbacks via CR/SR/DR rw functions
#
# @ ID: Unique numeric ID for peripheral. 
#
# @ <path>: Refers to the peripheral's path to a TOML file that 
#           defines its [hardware] and [interrupts] table templates completely.
#           You can use "peripherals/uart.toml" as an example for template syntax.
#
# periph0: Reserved peripheral key 

periph0 = ["default", true, 0, "peripherals/<peripheral>.toml"]
periph1 = ["uart", true, 1, "peripherals/uart.toml"]
periph2 = ["test", true, 2, "peripherals/test.toml"]
periph3 = ["<peripheral>", false, 3, "peripherals/<peripheral>.toml"]
periph4 = ["<peripheral>", false, 4, "peripherals/<peripheral>.toml"]
periph5 = ["<peripheral>", false, 5, "peripherals/<peripheral>.toml"]
periph6 = ["<peripheral>", false, 6, "peripherals/<peripheral>.toml"]
periph7 = ["<peripheral>", false, 7, "peripherals/<peripheral>.toml"]
periph8 = ["<peripheral>", false, 8, "peripherals/<peripheral>.toml"]
periph9 = ["<peripheral>", false, 9, "peripherals/<peripheral>.toml"]
periph10 = ["<peripheral>", false, 10, "peripherals/<peripheral>.toml"]
periph11 = ["<peripheral>", false, 11, "peripherals/<peripheral>.toml"]
periph12 = ["<peripheral>", false, 12, "peripherals/<peripheral>.toml"]
periph13 = ["<peripheral>", false, 13, "peripherals/<peripheral>.toml"]
periph14 = ["<peripheral>", false, 14, "peripherals/<peripheral>.toml"]
periph15 = ["<peripheral>", false, 15, "peripherals/<peripheral>.toml"]
periph16 = ["<peripheral>", false, 16, "peripherals/<peripheral>.toml"]
periph17 = ["<peripheral>", false, 17, "peripherals/<peripheral>.toml"]
periph18 = ["<peripheral>", false, 18, "peripherals/<peripheral>.toml"]
periph19 = ["<peripheral>", false, 19, "peripherals/<peripheral>.toml"]
periph20 = ["<peripheral>", false, 20, "peripherals/<peripheral>.toml"]
periph21 = ["<peripheral>", false, 21, "peripherals/<peripheral>.toml"]
periph22 = ["<peripheral>", false, 22, "peripherals/<peripheral>.toml"]
periph23 = ["<peripheral>", false, 23, "peripherals/<peripheral>.toml"]
periph24 = ["<peripheral>", false, 24, "peripherals/<peripheral>.toml"]
periph25 = ["<peripheral>", false, 25, "peripherals/<peripheral>.toml"]
periph26 = ["<peripheral>", false, 26, "peripherals/<peripheral>.toml"]
periph27 = ["<peripheral>", false, 27, "peripherals/<peripheral>.toml"]
periph28 = ["<peripheral>", false, 28, "peripherals/<peripheral>.toml"]
periph29 = ["<peripheral>", false, 29, "peripherals/<peripheral>.toml"]
periph30 = ["<peripheral>", false, 30, "peripherals/<peripheral>.toml"]
periph31 = ["<peripheral>", false, 31, "peripherals/<peripheral>.toml"]
periph32 = ["<peripheral>", false, 32, "peripherals/<peripheral>.toml"]
periph33 = ["<peripheral>", false, 33, "peripherals/<peripheral>.toml"]
periph34 = ["<peripheral>", false, 34, "peripherals/<peripheral>.toml"]
periph35 = ["<peripheral>", false, 35, "peripherals/<peripheral>.toml"]
periph36 = ["<peripheral>", false, 36, "peripherals/<peripheral>.toml"]
periph37 = ["<peripheral>", false, 37, "peripherals/<peripheral>.toml"]
periph38 = ["<peripheral>", false, 38, "peripherals/<peripheral>.toml"]
periph39 = ["<peripheral>", false, 39, "peripherals/<peripheral>.toml"]
periph40 = ["<peripheral>", false, 40, "peripherals/<peripheral>.toml"]
periph41 = ["<peripheral>", false, 41, "peripherals/<peripheral>.toml"]
periph42 = ["<peripheral>", false, 42, "peripherals/<peripheral>.toml"]
periph43 = ["<peripheral>", false, 43, "peripherals/<peripheral>.toml"]
periph44 = ["<peripheral>", false, 44, "peripherals/<peripheral>.toml"]
periph45 = ["<peripheral>", false, 45, "peripherals/<peripheral>.toml"]
periph46 = ["<peripheral>", false, 46, "peripherals/<peripheral>.toml"]
periph47 = ["<peripheral>", false, 47, "peripherals/<peripheral>.toml"]
periph48 = ["<peripheral>", false, 48, "peripherals/<peripheral>.toml"]
periph49 = ["<peripheral>", false, 49, "peripherals/<peripheral>.toml"]
periph50 = ["<peripheral>", false, 50, "peripherals/<peripheral>.toml"]
periph51 = ["<peripheral>", false, 51, "peripherals/<peripheral>.toml"]
periph52 = ["<peripheral>", false, 52, "peripherals/<peripheral>.toml"]
periph53 = ["<peripheral>", false, 53, "peripherals/<peripheral>.toml"]
periph54 = ["<peripheral>", false, 54, "peripherals/<peripheral>.toml"]
periph55 = ["<peripheral>", false, 55, "peripherals/<peripheral>.toml"]
periph56 = ["<peripheral>", false, 56, "peripherals/<peripheral>.toml"]
periph57 = ["<peripheral>", false, 57, "peripherals/<peripheral>.toml"]
periph58 = ["<peripheral>", false, 58, "peripherals/<peripheral>.toml"]
periph59 = ["<peripheral>", false, 59, "peripherals/<peripheral>.toml"]
periph60 = ["<peripheral>", false, 60, "peripherals/<peripheral>.toml"]
periph61 = ["<peripheral>", false, 61, "peripherals/<peripheral>.toml"]
periph62 = ["<peripheral>", false, 62, "peripherals/<peripheral>.toml"]
periph63 = ["<peripheral>", false, 63, "peripherals/<peripheral>.toml"]
periph64 = ["<peripheral>", false, 64, "peripherals/<peripheral>.toml"]
periph65 = ["<peripheral>", false, 65, "peripherals/<peripheral>.toml"]
periph66 = ["<peripheral>", false, 66, "peripherals/<peripheral>.toml"]
periph67 = ["<peripheral>", false, 67, "peripherals/<peripheral>.toml"]
periph68 = ["<peripheral>", false, 68, "peripherals/<peripheral>.toml"]
periph69 = ["<peripheral>", false, 69, "peripherals/<peripheral>.toml"]
periph70 = ["<peripheral>", false, 70, "peripherals/<peripheral>.toml"]
periph71 = ["<peripheral>", false, 71, "peripherals/<peripheral>.toml"]
periph72 = ["<peripheral>", false, 72, "peripherals/<peripheral>.toml"]
periph73 = ["<peripheral>", false, 73, "peripherals/<peripheral>.toml"]
periph74 = ["<peripheral>", false, 74, "peripherals/<peripheral>.toml"]
periph75 = ["<peripheral>", false, 75, "peripherals/<peripheral>.toml"]
periph76 = ["<peripheral>", false, 76, "peripherals/<peripheral>.toml"]
periph77 = ["<peripheral>", false, 77, "peripherals/<peripheral>.toml"]
periph78 = ["<peripheral>", false, 78, "peripherals/<peripheral>.toml"]
periph79 = ["<peripheral>", false, 79, "peripherals/<peripheral>.toml"]
periph80 = ["<peripheral>", false, 80, "peripherals/<peripheral>.toml"]
periph81 = ["<peripheral>", false, 81, "peripherals/<peripheral>.toml"]
periph82 = ["<peripheral>", false, 82, "peripherals/<peripheral>.toml"]
periph83 = ["<peripheral>", false, 83, "peripherals/<peripheral>.toml"]
periph84 = ["<peripheral>", false, 84, "peripherals/<peripheral>.toml"]
periph85 = ["<peripheral>", false, 85, "peripherals/<peripheral>.toml"]
periph86 = ["<peripheral>", false, 86, "peripherals/<peripheral>.toml"]
periph87 = ["<peripheral>", false, 87, "peripherals/<peripheral>.toml"]
periph88 = ["<peripheral>", false, 88, "peripherals/<peripheral>.toml"]
periph89 = ["<peripheral>", false, 89, "peripherals/<peripheral>.toml"]
periph90 = ["<peripheral>", false, 90, "peripherals/<peripheral>.toml"]
periph91 = ["<peripheral>", false, 91, "peripherals/<peripheral>.toml"]
periph92 = ["<peripheral>", false, 92, "peripherals/<peripheral>.toml"]
periph93 = ["<peripheral>", false, 93, "peripherals/<peripheral>.toml"]
periph94 = ["<peripheral>", false, 94, "peripherals/<peripheral>.toml"]
periph95 = ["<peripheral>", false, 95, "peripherals/<peripheral>.toml"]
periph96 = ["<peripheral>", false, 96, "peripherals/<peripheral>.toml"]
periph97 = ["<peripheral>", false, 97, "peripherals/<peripheral>.toml"]
periph98 = ["<peripheral>", false, 98, "peripherals/<peripheral>.toml"]
periph99 = ["<peripheral>", false, 99, "peripherals/<peripheral>.toml"]
periph100 = ["<peripheral>", false, 100, "peripherals/<peripheral>.toml"]
periph101 = ["<peripheral>", false, 101, "peripherals/<peripheral>.toml"]
periph102 = ["<peripheral>", false, 102, "peripherals/<peripheral>.toml"]
periph103 = ["<peripheral>", false, 103, "peripherals/<peripheral>.toml"]
periph104 = ["<peripheral>", false, 104, "peripherals/<peripheral>.toml"]
periph105 = ["<peripheral>", false, 105, "peripherals/<peripheral>.toml"]
periph106 = ["<peripheral>", false, 106, "peripherals/<peripheral>.toml"]
periph107 = ["<peripheral>", false, 107, "peripherals/<peripheral>.toml"]
periph108 = ["<peripheral>", false, 108, "peripherals/<peripheral>.toml"]
periph109 = ["<peripheral>", false, 109, "peripherals/<peripheral>.toml"]
periph110 = ["<peripheral>", false, 110, "peripherals/<peripheral>.toml"]
periph111 = ["<peripheral>", false, 111, "peripherals/<peripheral>.toml"]
periph112 = ["<peripheral>", false, 112, "peripherals/<peripheral>.toml"]
periph113 = ["<peripheral>", false, 113, "peripherals/<peripheral>.toml"]
periph114 = ["<peripheral>", false, 114, "peripherals/<peripheral>.toml"]
periph115 = ["<peripheral>", false, 115, "peripherals/<peripheral>.toml"]
periph116 = ["<peripheral>", false, 116, "peripherals/<peripheral>.toml"]
periph117 = ["<peripheral>", false, 117, "peripherals/<peripheral>.toml"]
periph118 = ["<peripheral>", false, 118, "peripherals/<peripheral>.toml"]
periph119 = ["<peripheral>", false, 119, "peripherals/<peripheral>.toml"]
periph120 = ["<peripheral>", false, 120, "peripherals/<peripheral>.toml"]
periph121 = ["<peripheral>", false, 121, "peripherals/<peripheral>.toml"]
periph122 = ["<peripheral>", false, 122, "peripherals/<peripheral>.toml"]
periph123 = ["<peripheral>", false, 123, "peripherals/<peripheral>.toml"]
periph124 = ["<peripheral>", false, 124, "peripherals/<peripheral>.toml"]
periph125 = ["<peripheral>", false, 125, "peripherals/<peripheral>.toml"]
periph126 = ["<peripheral>", false, 126, "peripherals/<peripheral>.toml"]
periph127 = ["<peripheral>", false, 127, "peripherals/<peripheral>.toml"]
periph128 = ["<peripheral>", false, 128, "peripherals/<peripheral>.toml"]
periph129 = ["<peripheral>", false, 129, "peripherals/<peripheral>.toml"]
periph130 = ["<peripheral>", false, 130, "peripherals/<peripheral>.toml"]
periph131 = ["<peripheral>", false, 131, "peripherals/<peripheral>.toml"]
periph132 = ["<peripheral>", false, 132, "peripherals/<peripheral>.toml"]
periph133 = ["<peripheral>", false, 133, "peripherals/<peripheral>.toml"]
periph134 = ["<peripheral>", false, 134, "peripherals/<peripheral>.toml"]
periph135 = ["<peripheral>", false, 135, "peripherals/<peripheral>.toml"]
periph136 = ["<peripheral>", false, 136, "peripherals/<peripheral>.toml"]
periph137 = ["<peripheral>", false, 137, "peripherals/<peripheral>.toml"]
periph138 = ["<peripheral>", false, 138, "peripherals/<peripheral>.toml"]
periph139 = ["<peripheral>", false, 139, "peripherals/<peripheral>.toml"]
periph140 = ["<peripheral>", false, 140, "peripherals/<peripheral>.toml"]
periph141 = ["<peripheral>", false, 141, "peripherals/<peripheral>.toml"]
periph142 = ["<peripheral>", false, 142, "peripherals/<peripheral>.toml"]
periph143 = ["<peripheral>", false, 143, "peripherals/<peripheral>.toml"]
periph144 = ["<peripheral>", false, 144, "peripherals/<peripheral>.toml"]
periph145 = ["<peripheral>", false, 145, "peripherals/<peripheral>.toml"]
periph146 = ["<peripheral>", false, 146, "peripherals/<peripheral>.toml"]
periph147 = ["<peripheral>", false, 147, "peripherals/<peripheral>.toml"]
periph148 = ["<peripheral>", false, 148, "peripherals/<peripheral>.toml"]
periph149 = ["<peripheral>", false, 149, "peripherals/<peripheral>.toml"]
periph150 = ["<peripheral>", false, 150, "peripherals/<peripheral>.toml"]
periph151 = ["<peripheral>", false, 151, "peripherals/<peripheral>.toml"]
periph152 = ["<peripheral>", false, 152, "peripherals/<peripheral>.toml"]
periph153 = ["<peripheral>", false, 153, "peripherals/<peripheral>.toml"]
periph154 = ["<peripheral>", false, 154, "peripherals/<peripheral>.toml"]
periph155 = ["<peripheral>", false, 155, "peripherals/<peripheral>.toml"]
periph156 = ["<peripheral>", false, 156, "peripherals/<peripheral>.toml"]
periph157 = ["<peripheral>", false, 157, "peripherals/<peripheral>.toml"]
periph158 = ["<peripheral>", false, 158, "peripherals/<peripheral>.toml"]
periph159 = ["<peripheral>", false, 159, "peripherals/<peripheral>.toml"]
periph160 = ["<peripheral>", false, 160, "peripherals/<peripheral>.toml"]
periph161 = ["<peripheral>", false, 161, "peripherals/<peripheral>.toml"]
periph162 = ["<peripheral>", false, 162, "peripherals/<peripheral>.toml"]
periph163 = ["<peripheral>", false, 163, "peripherals/<peripheral>.toml"]
periph164 = ["<peripheral>", false, 164, "peripherals/<peripheral>.toml"]
periph165 = ["<peripheral>", false, 165, "peripherals/<peripheral>.toml"]
periph166 = ["<peripheral>", false, 166, "peripherals/<peripheral>.toml"]
periph167 = ["<peripheral>", false, 167, "peripherals/<peripheral>.toml"]
periph168 = ["<peripheral>", false, 168, "peripherals/<peripheral>.toml"]
periph169 = ["<peripheral>", false, 169, "peripherals/<peripheral>.toml"]
periph170 = ["<peripheral>", false, 170, "peripherals/<peripheral>.toml"]
periph171 = ["<peripheral>", false, 171, "peripherals/<peripheral>.toml"]
periph172 = ["<peripheral>", false, 172, "peripherals/<peripheral>.toml"]
periph173 = ["<peripheral>", false, 173, "peripherals/<peripheral>.toml"]
periph174 = ["<peripheral>", false, 174, "peripherals/<peripheral>.toml"]
periph175 = ["<peripheral>", false, 175, "peripherals/<peripheral>.toml"]
periph176 = ["<peripheral>", false, 176, "peripherals/<peripheral>.toml"]
periph177 = ["<peripheral>", false, 177, "peripherals/<peripheral>.toml"]
periph178 = ["<peripheral>", false, 178, "peripherals/<peripheral>.toml"]
periph179 = ["<peripheral>", false, 179, "peripherals/<peripheral>.toml"]
periph180 = ["<peripheral>", false, 180, "peripherals/<peripheral>.toml"]
periph181 = ["<peripheral>", false, 181, "peripherals/<peripheral>.toml"]
periph182 = ["<peripheral>", false, 182, "peripherals/<peripheral>.toml"]
periph183 = ["<peripheral>", false, 183, "peripherals/<peripheral>.toml"]
periph184 = ["<peripheral>", false, 184, "peripherals/<peripheral>.toml"]
periph185 = ["<peripheral>", false, 185, "peripherals/<peripheral>.toml"]
periph186 = ["<peripheral>", false, 186, "peripherals/<peripheral>.toml"]
periph187 = ["<peripheral>", false, 187, "peripherals/<peripheral>.toml"]
periph188 = ["<peripheral>", false, 188, "peripherals/<peripheral>.toml"]
periph189 = ["<peripheral>", false, 189, "peripherals/<peripheral>.toml"]
periph190 = ["<peripheral>", false, 190, "peripherals/<peripheral>.toml"]
periph191 = ["<peripheral>", false, 191, "peripherals/<peripheral>.toml"]
periph192 = ["<peripheral>", false, 192, "peripherals/<peripheral>.toml"]
periph193 = ["<peripheral>", false, 193, "peripherals/<peripheral>.toml"]
periph194 = ["<peripheral>", false, 194, "peripherals/<peripheral>.toml"]
periph195 = ["<peripheral>", false, 195, "peripherals/<peripheral>.toml"]
periph196 = ["<peripheral>", false, 196, "peripherals/<peripheral>.toml"]
periph197 = ["<peripheral>", false, 197, "peripherals/<peripheral>.toml"]
periph198 = ["<peripheral>", false, 198, "peripherals/<peripheral>.toml"]
periph199 = ["<peripheral>", false, 199, "peripherals/<peripheral>.toml"]
periph200 = ["<peripheral>", false, 200, "peripherals/<peripheral>.toml"]
periph201 = ["<peripheral>", false, 201, "peripherals/<peripheral>.toml"]
periph202 = ["<peripheral>", false, 202, "peripherals/<peripheral>.toml"]
periph203 = ["<peripheral>", false, 203, "peripherals/<peripheral>.toml"]
periph204 = ["<peripheral>", false, 204, "peripherals/<peripheral>.toml"]
periph205 = ["<peripheral>", false, 205, "peripherals/<peripheral>.toml"]
periph206 = ["<peripheral>", false, 206, "peripherals/<peripheral>.toml"]
periph207 = ["<peripheral>", false, 207, "peripherals/<peripheral>.toml"]
periph208 = ["<peripheral>", false, 208, "peripherals/<peripheral>.toml"]
periph209 = ["<peripheral>", false, 209, "peripherals/<peripheral>.toml"]
periph210 = ["<peripheral>", false, 210, "peripherals/<peripheral>.toml"]
periph211 = ["<peripheral>", false, 211, "peripherals/<peripheral>.toml"]
periph212 = ["<peripheral>", false, 212, "peripherals/<peripheral>.toml"]
periph213 = ["<peripheral>", false, 213, "peripherals/<peripheral>.toml"]
periph214 = ["<peripheral>", false, 214, "peripherals/<peripheral>.toml"]
periph215 = ["<peripheral>", false, 215, "peripherals/<peripheral>.toml"]
periph216 = ["<peripheral>", false, 216, "peripherals/<peripheral>.toml"]
periph217 = ["<peripheral>", false, 217, "peripherals/<peripheral>.toml"]
periph218 = ["<peripheral>", false, 218, "peripherals/<peripheral>.toml"]
periph219 = ["<peripheral>", false, 219, "peripherals/<peripheral>.toml"]
periph220 = ["<peripheral>", false, 220, "peripherals/<peripheral>.toml"]
periph221 = ["<peripheral>", false, 221, "peripherals/<peripheral>.toml"]
periph222 = ["<peripheral>", false, 222, "peripherals/<peripheral>.toml"]
periph223 = ["<peripheral>", false, 223, "peripherals/<peripheral>.toml"]
periph224 = ["<peripheral>", false, 224, "peripherals/<peripheral>.toml"]
periph225 = ["<peripheral>", false, 225, "peripherals/<peripheral>.toml"]
periph226 = ["<peripheral>", false, 226, "peripherals/<peripheral>.toml"]
periph227 = ["<peripheral>", false, 227, "peripherals/<peripheral>.toml"]
periph228 = ["<peripheral>", false, 228, "peripherals/<peripheral>.toml"]
periph229 = ["<peripheral>", false, 229, "peripherals/<peripheral>.toml"]
periph230 = ["<peripheral>", false, 230, "peripherals/<peripheral>.toml"]
periph231 = ["<peripheral>", false, 231, "peripherals/<peripheral>.toml"]
periph232 = ["<peripheral>", false, 232, "peripherals/<peripheral>.toml"]
periph233 = ["<peripheral>", false, 233, "peripherals/<peripheral>.toml"]
periph234 = ["<peripheral>", false, 234, "peripherals/<peripheral>.toml"]
periph235 = ["<peripheral>", false, 235, "peripherals/<peripheral>.toml"]
periph236 = ["<peripheral>", false, 236, "peripherals/<peripheral>.toml"]
periph237 = ["<peripheral>", false, 237, "peripherals/<peripheral>.toml"]
periph238 = ["<peripheral>", false, 238, "peripherals/<peripheral>.toml"]
periph239 = ["<peripheral>", false, 239, "peripherals/<peripheral>.toml"]
periph240 = ["<peripheral>", false, 240, "peripherals/<peripheral>.toml"]
periph241 = ["<peripheral>", false, 241, "peripherals/<peripheral>.toml"]
periph242 = ["<peripheral>", false, 242, "peripherals/<peripheral>.toml"]
periph243 = ["<peripheral>", false, 243, "peripherals/<peripheral>.toml"]
periph244 = ["<peripheral>", false, 244, "peripherals/<peripheral>.toml"]
periph245 = ["<peripheral>", false, 245, "peripherals/<peripheral>.toml"]
periph246 = ["<peripheral>", false, 246, "peripherals/<peripheral>.toml"]
periph247 = ["<peripheral>", false, 247, "peripherals/<peripheral>.toml"]
periph248 = ["<peripheral>", false, 248, "peripherals/<peripheral>.toml"]
periph249 = ["<peripheral>", false, 249, "peripherals/<peripheral>.toml"]
periph250 = ["<peripheral>", false, 250, "peripherals/<peripheral>.toml"]
periph251 = ["<peripheral>", false, 251, "peripherals/<peripheral>.toml"]
periph252 = ["<peripheral>", false, 252, "peripherals/<peripheral>.toml"]
periph253 = ["<peripheral>", false, 253, "peripherals/<peripheral>.toml"]
periph254 = ["<peripheral>", false, 254, "peripherals/<peripheral>.toml"]
periph255 = ["<peripheral>", false, 255, "peripherals/<peripheral>.toml"]
