[test.hardware]
    
[test.interrupts]
[test.interrupts.RX]
IRQn = "none"
Emulation_Mode = "full"
Intr_Enable = {CR = "none", bit = 0}
Intr_Disable = {CR = "none", bit = 0}
Intr_Status = {SR = "none", bit = 0}
Intr_Clear = {CR = "none"}    

[test.interrupts.TX]
IRQn = "none"
Emulation_Mode = "full"
Intr_Enable = {CR = "none", bit = 0}
Intr_Disable = {CR = "none", bit = 0}
Intr_Status = {SR = "none", bit = 0} 
Intr_Clear = {CR = "none"}    

